### ISSUE TITLE
lib faltante owl.carousel

### ISSUE THREAD

**Issue by thiagogomesverissimo** [fflch/cem-theme#1]
themes/contrib/cem-theme/vendor/OwlCarousel/dist/owl.carousel.min.js

**Comment by thiagogomesverissimo** [comment]
```
font-awesome:
  remote: https://fortawesome.github.io/Font-Awesome/
  version: 4.5.0
  license:
    name: MIT
    url: https://fortawesome.github.io/Font-Awesome/license/
    gpl-compatible: true
  css:
    theme:
      https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css: { type: external, minified: true }
```
